### ISSUE TITLE
Not work limiting example of -7 to 21 hours

### ISSUE THREAD

**Issue by jaimbox** [mrwhite1/sampleforweekview#1]
I tested the example and does not work, it always shows the hours from 12am to 11pm, please help.

`Calendar cal = Calendar.getInstance();`
`cal.add(Calendar.DATE, -7);`
`mWeekView.setMinDate(cal);`
`Calendar c = Calendar.getInstance();`
`c.add(Calendar.DATE,21);`
`mWeekView.setMaxDate(c);`

![screenshot_20160822-234036](https://cloud.githubusercontent.com/assets/7720754/17880591/77abee6c-68c2-11e6-9491-0e79a74627d6.png)

**Comment by jaimbox** [comment]
I've realized that I misunderstood your example, you would have something that can help me with this?

**Comment by mrwhite1** [comment]
if you want to limit vertical scroll then you have to do it modifying source code. there is some issues regarding that in original library i guess.
